### ISSUE TITLE
Create CONTRIBUTING.md, ISSUE_TEMPLATE.md, and PULL_REQUEST_TEMPLATE.md.

### ISSUE THREAD

**Issue by octalmage** [octalmage/robotjs#203]
- [x] [Contributing guidelines](https://github.com/blog/1184-contributing-guidelines)
- [x] [Issue template](https://github.com/blog/2111-issue-and-pull-request-templates)
- [ ] [Pull request template](https://github.com/blog/2111-issue-and-pull-request-templates)

All of these will help us work more efficiently.

**Comment by octalmage** [comment]
I'm going to close this, with the new built-in review system I don't think we need a pull request template for now.
